### ISSUE TITLE
How to access a user's file system?

### ISSUE THREAD

**Issue by JulianKingman** [luzifer-docker/sftp-share#2]
I set up SFTP per your example, and it shows me almost everything. The only things I can't access are the root folder (OK, make sense) and the /home/core folder (core is  a user in CoreOs). It's the /home/core folder that I need access to, any idea how to allow that?

**Comment by Luzifer** [comment]
This container is not intended to access all folders on the host system. It only allows access to the volume mounted to the `/data` volume inside the docker container. So if you want to access hosts `/home/core` folder you need to mount it to the `/data` volume:

``` bash
$ docker run \
    -v /home/core:/data \
    -p 2022:22 \
    -e USER=myuser \
    -e PASS=myverysecretpassword \
    luzifer/sftp-share
```

If you ran the container that way you will see the same contents in `/data` as you're seeing on your host in `/home/core`.

**Comment by JulianKingman** [comment]
That makes sense. How would I connect it to a data container, would I use the --volumes-from tag somehow?

**Comment by Luzifer** [comment]
You could create a container exposing `/data` directory, storing the data into that directory in your data container an then use `--volumes-from` option to connect the two containers together.

See more information at https://docs.docker.com/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container

**Comment by JulianKingman** [comment]
How do credentials work with a data container?

**Comment by Luzifer** [comment]
The same. You specify your credentials in the sftp-container. The data-container just is a storage like if you mounted the data directly from the host.

**Comment by JulianKingman** [comment]
Sorry if this question is naive, but how do you get the credentials connected to the container? I mean, you have to set up a user with the same credentials as the SFTP container, right? Or… can I --link the container and specify any credentials I please and it will work? Sorry if this is really basic, I’m getting used to docker :)

**Comment by Luzifer** [comment]
You can specify whatever you want for this container. There is no connection to the system credentials.
